model_name_or_path: "mistralai/Mistral-7B-v0.1"
data_path: "./data/zsre/zsre_3k.json"
save_model_dir: "./saves/mistral_zsre3k"

layer: 23
rewrite_module: "model.layers.{}"

lr: 5.0e-5
batch_size: 100
num_steps: 25
device: 0
