model_name_or_path: "Qwen/Qwen2.5-7B-Instruct"
data_path: "./zsre/zsre_eval_3k.json"
save_model_dir: "./saves/qwen_zsre3k"

layer: 6
rewrite_module: "model.layers.{}.mlp.down_proj.weight"

lr: 5.0e-4
batch_size: 100
num_steps: 25
device: 0
